<a href="https://colab.research.google.com/github/SSGrady/PyTorchFundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
!nvidia-smi

Mon Feb 26 10:35:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Introduction to Tensors
### Tensors are a way of representing multi-dimensional data

PyTorch tensors are created using `torch.Tensor()`  = https://pytorch.org/docs/stable/tensors.html


In [3]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

8

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
# number of square brackets
vector.ndim

1

In [11]:
# 2x1 elements
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([7, 8])

In [19]:
# 2x2 elements
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,8,12]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 4,  8, 12]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [ 4,  8, 12]])

Practice making any given shape of Tensor

*Then predict and check via print statements: ndim, shape, indices of Tensor*

In [27]:
TENSOR = torch.tensor([[[6,4,12],[8,3,2],[5,0,9]],
          [[1,6,7],[7,10,11],[13,2,15]],
          [[2,2,2],[3,3,3],[4,4,4]]])
TENSOR

tensor([[[ 6,  4, 12],
         [ 8,  3,  2],
         [ 5,  0,  9]],

        [[ 1,  6,  7],
         [ 7, 10, 11],
         [13,  2, 15]],

        [[ 2,  2,  2],
         [ 3,  3,  3],
         [ 4,  4,  4]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([3, 3, 3])

### Random tensors

Why random tensors?
They're important because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [31]:
# Create a random tensor of size (3,4)
# random_tensor = torch.rand(3,4)
random_tensor = torch.rand(1,8,8)
random_tensor

tensor([[[0.2988, 0.6781, 0.0462, 0.7721, 0.8576, 0.4158, 0.0839, 0.5960],
         [0.8253, 0.4538, 0.3709, 0.7858, 0.4024, 0.8992, 0.8969, 0.7413],
         [0.1917, 0.8902, 0.1306, 0.5950, 0.2252, 0.2570, 0.2996, 0.1276],
         [0.5600, 0.4088, 0.3334, 0.2996, 0.7561, 0.0296, 0.1551, 0.4670],
         [0.1915, 0.5346, 0.5951, 0.5269, 0.2952, 0.3078, 0.4200, 0.1452],
         [0.6358, 0.3465, 0.6877, 0.7125, 0.8423, 0.0534, 0.5732, 0.1229],
         [0.0630, 0.2884, 0.6407, 0.0148, 0.1088, 0.5863, 0.7168, 0.9988],
         [0.3179, 0.5412, 0.9410, 0.1358, 0.2930, 0.8969, 0.0822, 0.5110]]])

In [34]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [38]:
# Create a tensor of all zeros - helpful when creating masks
zeros = torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [39]:
# Create a tensor of all ones
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like


In [42]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=10, step =1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

Measures the precision in computing i.e. how much detail is in numbers

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [55]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                  dtype= None, # what datatype is the tensor (e.g. float32 or float16)
                                  device= None, # by deault it uses cpu (could also use cuda) -> what device is your tensor on?
                                  requires_grad=False) # whether or not to track gradients with this tensors operation

float_32_tensor, float_32_tensor.dtype # by default float 32 tensor is default

(tensor([3., 6., 9.]), torch.float32)

In [56]:
# converting float 32 tensor to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)